apiVersion: apps/v1
kind: Deployment
metadata:
  name: ookky6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ookky6
  template:
    metadata:
      labels:
        app: ookky6
    spec:
      containers:
      - image: okteto.dev/ookky6:latest
        name: ookky6
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4ce520dc-9e84-41a5-883c-6876a38bfc53"
        - name: Vless_Path
          value: "/vl432"
        - name: Vmess_UUID
          value: "4ce520dc-9e84-41a5-883c-6876a38bfc53"
        - name: Vmess_Path
          value: "/vm431"
        - name: Share_Path
          value: "/v2link"
