apiVersion: v1
kind: Service
metadata:
  name: ookky6
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ookky6"
    port: 8080
  selector:
    app: ookky6
